sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGSAFGGi7iMhL6biYCp
    access-key-secret: KymEP0Jx6Ijne8CO9EuFe6kmHkjhfP
    bucket-name: sky-thp
#    endpoint: oss-cn-shenzhen.aliyuncs.com
#    access-key-id: LTAI5tHzX4fMjySKcCoCvYci
#    access-key-secret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
#    bucket-name: cangqiongwaimaipbj
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: wxd472c0ca0c0b1f29
    secret: 6d2f93105b9c125d70a62b0ae31e4e97
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php